name: CI
on:
  push:
    branches:
      - master
  pull_request: {}
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://postgres@postgres/CeaselessPrayer_test
    services:
      # Based on https://help.github.com/en/actions/configuring-and-managing-workflows/creating-postgresql-service-containers
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: bundle-use-ruby-ubuntu-latest-${{ hashFiles('.ruby-version') }}-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            bundle-use-ruby-ubuntu-latest-${{ hashFiles('.ruby-version') }}-
      - name: bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - run: bundle exec rake db:setup
      - run: bundle exec rake
